// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: solid.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Solid_State_FullMethodName = "/Solid/State"
)

// SolidClient is the client API for Solid service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SolidClient interface {
	State(ctx context.Context, in *StateRequest, opts ...grpc.CallOption) (*StateResponse, error)
}

type solidClient struct {
	cc grpc.ClientConnInterface
}

func NewSolidClient(cc grpc.ClientConnInterface) SolidClient {
	return &solidClient{cc}
}

func (c *solidClient) State(ctx context.Context, in *StateRequest, opts ...grpc.CallOption) (*StateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StateResponse)
	err := c.cc.Invoke(ctx, Solid_State_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SolidServer is the server API for Solid service.
// All implementations must embed UnimplementedSolidServer
// for forward compatibility.
type SolidServer interface {
	State(context.Context, *StateRequest) (*StateResponse, error)
	mustEmbedUnimplementedSolidServer()
}

// UnimplementedSolidServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSolidServer struct{}

func (UnimplementedSolidServer) State(context.Context, *StateRequest) (*StateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method State not implemented")
}
func (UnimplementedSolidServer) mustEmbedUnimplementedSolidServer() {}
func (UnimplementedSolidServer) testEmbeddedByValue()               {}

// UnsafeSolidServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SolidServer will
// result in compilation errors.
type UnsafeSolidServer interface {
	mustEmbedUnimplementedSolidServer()
}

func RegisterSolidServer(s grpc.ServiceRegistrar, srv SolidServer) {
	// If the following call pancis, it indicates UnimplementedSolidServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Solid_ServiceDesc, srv)
}

func _Solid_State_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SolidServer).State(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Solid_State_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SolidServer).State(ctx, req.(*StateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Solid_ServiceDesc is the grpc.ServiceDesc for Solid service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Solid_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Solid",
	HandlerType: (*SolidServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "State",
			Handler:    _Solid_State_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "solid.proto",
}
